"""
Deterministic account report assembly for the BDR pipeline.

This module is intentionally pure: no Streamlit, no network calls, no LLM calls,
no filesystem writes. It formats existing pipeline state into a founder-readable
Markdown artifact and exposes small helpers used by the UI.
"""
from __future__ import annotations

import re
from typing import Any

from app.tenants.schema import TenantConfig


PRIORITY_LABELS = {
    "high_priority": "High Priority",
    "review": "Review",
    "needs_more_research": "Needs More Research",
    "do_not_send_yet": "Do Not Send Yet",
}

GATE_LABELS = {
    "approved": "Approved",
    "needs_edit": "Needs Edit",
    "needs_more_research": "Needs More Research",
    "do_not_send_yet": "Do Not Send Yet",
}

CHECKLIST = [
    "Verify recipient and email.",
    "Verify source-backed claims.",
    "Edit or remove unsupported personalization.",
    "Approve only if the gate verdict allows it.",
    "Do not claim reply/meeting outcomes without campaign data.",
]

LIMITATIONS = [
    "No reply-rate or meeting-rate claims yet.",
    "Evidence confidence is source-presence based, not external verification.",
    "Human review required before sending.",
]


def build_account_report_markdown(state: dict, tenant: TenantConfig) -> str:
    """Build a deterministic Markdown report from already-produced state."""
    enrichment = _get(state, "enrichment")
    strategy = _get(state, "strategy")
    card = _get(state, "card")
    critic_result = _get(state, "critic_result")
    gate = _get(critic_result, "quality_gate")
    account_score = _get(enrichment, "account_score")

    company = _text(_get(enrichment, "company") or _get(state, "company"), "Unknown account")
    industry = _text(_get(enrichment, "industry") or _get(state, "industry"), "Unknown")
    priority = _get(account_score, "priority_label") or ""
    verdict = _get(gate, "verdict") or ""
    safe_to_send = bool(_get(gate, "safe_to_send")) if gate else False
    next_action = determine_next_action(account_score, gate, enrichment)
    contact = select_recommended_contact(_get(enrichment, "contacts") or [], tenant)
    evidence = select_top_evidence_cards(_get(enrichment, "evidence_cards") or [], limit=6)
    observed = [c for c in evidence if _get(c, "support_type") == "observed"]
    derived = [c for c in evidence if _get(c, "support_type") != "observed"]
    sequence = _get(card, "sequence")

    lines: list[str] = [
        f"# BDR Account Report: {company}",
        "",
        "## Metadata",
        f"- Industry: {industry}",
        f"- Tenant / product: {_text(_get(tenant, 'brand.name'), tenant.brand.name)}",
        f"- Persona: {_text(_get(tenant, 'persona.title'), tenant.persona.title)}",
        "- Generated by BDR Pipeline",
        "- Manual review required before sending",
        "",
        "## Decision Summary",
        f"- Account score: {_score_value(account_score)}/100",
        f"- Priority: {format_priority(priority)}",
        f"- Gate verdict: {format_gate_verdict(verdict) if gate else 'Run Critic / Manual Review Required'}",
        f"- Safe to send: {'Yes' if safe_to_send else 'No'}",
        f"- Recommended next action: {next_action}",
        "",
        "## Why This Account",
        f"- ICP fit rationale: {_component_rationale(account_score, 'icp_fit')}",
        f"- Pain evidence rationale: {_component_rationale(account_score, 'pain_evidence')}",
        f"- Trigger strength rationale: {_component_rationale(account_score, 'trigger_strength')}",
        f"- Strategy recommended angle: {_strategy_angle(strategy)}",
        f"- Strategy pain signal: {_text(_get(strategy, 'pain_signal'), 'No strategy pain signal available.')}",
        "",
        "## Evidence Highlights",
    ]

    if observed:
        lines.extend(["", "### Observed / Source-Backed Evidence"])
        lines.extend(_format_evidence_markdown(observed))
    else:
        lines.append("- No observed/source-backed evidence cards were available.")

    if derived:
        lines.extend(["", "### Derived / Internal Scoring Evidence"])
        lines.extend(_format_evidence_markdown(derived))

    lines.extend([
        "",
        "## Recommended Contact",
        *_format_contact_markdown(contact),
        "",
        "## Outreach Recommendation",
        f"- Recommended angle: {_text(_get(sequence, 'recommended_angle') or _get(strategy, 'angle_name'), 'No angle available.')}",
        f"- Entry persona: {_text(_get(sequence, 'entry_persona') or _get(strategy, 'cpo_hypothesis'), tenant.persona.title)}",
        "",
    ])
    lines.extend(_format_sequence_markdown(sequence))

    risk_flags = _get(gate, "risk_flags") or []
    required_edits = _get(gate, "required_edits") or []
    lines.extend([
        "",
        "## Quality + Risk",
        f"- Critic overall quality: {_quality_value(critic_result)}",
        f"- Gate summary: {_text(_get(gate, 'summary'), 'No quality gate available.')}",
        f"- Unsupported claim count: {_get(gate, 'unsupported_claim_count') if gate else 'Unknown'}",
        "",
        "### Required Edits",
    ])
    lines.extend(_format_string_list(required_edits, "No required edits were returned."))
    lines.extend(["", "### Risk Flags"])
    lines.extend(_format_risk_flags(risk_flags))

    lines.extend([
        "",
        "## Human Approval Checklist",
        *[f"- {item}" for item in CHECKLIST],
        "",
        "## Limitations",
        *[f"- {item}" for item in LIMITATIONS],
        "",
    ])
    return "\n".join(lines)


def build_report_filename(company: str) -> str:
    """Return a safe deterministic Markdown filename."""
    slug = re.sub(r"[^a-z0-9]+", "-", (company or "account").lower()).strip("-")
    return f"bdr-account-report-{slug or 'account'}.md"


def select_top_evidence_cards(cards: list[Any], limit: int = 6) -> list[Any]:
    """Select top evidence deterministically for report display."""
    confidence_rank = {"high": 0, "medium": 1, "low": 2}
    support_rank = {"observed": 0, "derived": 1, "inferred": 2}
    source_rank = {
        "live_signal": 0,
        "job_signal": 1,
        "contact": 2,
        "manual_trigger": 3,
        "icp_score": 4,
    }

    def sort_key(card: Any) -> tuple[Any, ...]:
        safe = 0 if bool(_get(card, "safe_to_use")) else 1
        support = support_rank.get(str(_get(card, "support_type") or ""), 9)
        confidence = confidence_rank.get(str(_get(card, "confidence_label") or ""), 9)
        source = source_rank.get(str(_get(card, "source_type") or ""), 9)
        score = -int(_get(card, "confidence_score") or 0)
        evidence_id = str(_get(card, "evidence_id") or "")
        return (safe, support, confidence, source, score, evidence_id)

    useful_cards = [card for card in cards if _get(card, "claim") or _get(card, "excerpt")]
    return sorted(useful_cards, key=sort_key)[:limit]


def select_recommended_contact(contacts: list[Any], tenant: TenantConfig) -> Any | None:
    """Pick the best contact using deterministic title, email, and confidence rules."""
    if not contacts:
        return None

    persona_terms = _title_terms([tenant.persona.title, *tenant.persona.title_alternates])
    seniority_rank = {
        "c_suite": 40,
        "executive": 35,
        "owner": 35,
        "founder": 35,
        "vp": 30,
        "vice_president": 30,
        "director": 20,
        "head": 18,
        "manager": 10,
    }

    def score(contact: Any) -> tuple[int, int, int, str]:
        title = str(_get(contact, "position") or _get(contact, "title") or "").lower()
        seniority = str(_get(contact, "seniority") or "").lower()
        email_bonus = 1000 if _get(contact, "email") else 0
        confidence = int(_get(contact, "confidence") or 0)
        relevance = 160 if any(term and term in title for term in persona_terms) else 0
        seniority_bonus = max((points for key, points in seniority_rank.items() if key in seniority or key in title), default=0)
        tie_breaker = str(_get(contact, "name") or _get(contact, "email") or "")
        return (email_bonus + relevance + seniority_bonus + confidence, confidence, relevance, tie_breaker)

    return sorted(contacts, key=score, reverse=True)[0]


def determine_next_action(account_score: Any, gate: Any, enrichment: Any | None = None) -> str:
    """Compute a cautious deterministic next action."""
    if not gate:
        return "Run critic or manually review before sending."

    verdict = _get(gate, "verdict") or ""
    if verdict == "do_not_send_yet":
        return "Do not send yet. Resolve risk flags and gather stronger evidence."
    if verdict == "needs_more_research":
        return "Gather stronger evidence before outreach."
    if verdict == "needs_edit":
        return "Edit required items, then re-review before sending."

    contacts = _get(enrichment, "contacts") or [] if enrichment else []
    if verdict == "approved" and not contacts:
        return "Human review, then manually discover a verified contact before sending."

    priority = _get(account_score, "priority_label") or ""
    if verdict == "approved" and priority in {"high_priority", "review"}:
        return "Human review, then approve/send manually."
    return "Human review required before any send."


def format_priority(priority: str) -> str:
    return PRIORITY_LABELS.get(priority or "", _readable(priority) or "Unknown")


def format_gate_verdict(verdict: str) -> str:
    return GATE_LABELS.get(verdict or "", _readable(verdict) or "Unknown")


def evidence_bucket_label(card: Any) -> str:
    support = _get(card, "support_type") or ""
    if support == "observed":
        return "Observed / source-backed"
    return "Derived / internal"


def _format_evidence_markdown(cards: list[Any]) -> list[str]:
    if not cards:
        return ["- No evidence cards available."]
    lines: list[str] = []
    for card in cards:
        source_url = _get(card, "source_url") or ""
        source_title = _get(card, "source_title") or "No source title"
        source = f"{source_title} ({source_url})" if source_url else source_title
        lines.extend([
            f"- {evidence_bucket_label(card)} evidence",
            f"  - Evidence ID: {_text(_get(card, 'evidence_id'), 'unknown')}",
            f"  - Confidence: {_readable(_get(card, 'confidence_label'))} ({_get(card, 'confidence_score') or 0}/100)",
            f"  - Support type: {_readable(_get(card, 'support_type'))}",
            f"  - Claim: {_text(_get(card, 'claim'), 'No claim available.')}",
            f"  - Source: {source}",
        ])
    return lines


def _format_contact_markdown(contact: Any | None) -> list[str]:
    if not contact:
        return [
            "- Name: No verified contact found",
            "- Warning: No contacts were found. Manual contact discovery is required before outreach.",
        ]
    confidence = int(_get(contact, "confidence") or 0)
    lines = [
        f"- Name: {_text(_get(contact, 'name'), 'Unknown')}",
        f"- Title: {_text(_get(contact, 'position') or _get(contact, 'title'), 'Unknown')}",
        f"- Email: {_text(_get(contact, 'email'), 'Not available')}",
        f"- Confidence: {confidence}",
        f"- LinkedIn URL: {_text(_get(contact, 'linkedin_url'), 'Not available')}",
    ]
    if confidence < 70 or not _get(contact, "email"):
        lines.append("- Warning: Contact confidence is low or email is missing. Verify manually before outreach.")
    return lines


def _format_sequence_markdown(sequence: Any) -> list[str]:
    touches = _get(sequence, "touches") or []
    if not touches:
        return ["No outreach sequence was drafted."]
    lines = [f"### {len(touches)}-Touch Sequence Summary"]
    for touch in touches:
        channel = _readable(_get(touch, "channel")) or "Touch"
        number = _get(touch, "touch_number") or "?"
        day = _get(touch, "day") if _get(touch, "day") is not None else "?"
        subject = _get(touch, "subject") or ""
        body = _get(touch, "body") or ""
        lines.extend([
            "",
            f"#### Touch {number}: Day {day} - {channel}",
        ])
        if subject:
            lines.append(f"Subject: {subject}")
        lines.extend(["", body or "No body available."])
    return lines


def _format_risk_flags(risk_flags: list[Any]) -> list[str]:
    if not risk_flags:
        return ["- No risk flags were returned."]
    lines: list[str] = []
    for flag in risk_flags:
        touch = _get(flag, "touch_number")
        touch_label = f" / Touch {touch}" if touch is not None else ""
        lines.extend([
            f"- {_readable(_get(flag, 'risk_type'))}{touch_label}",
            f"  - Severity: {_readable(_get(flag, 'severity'))}",
            f"  - Rationale: {_text(_get(flag, 'rationale'), 'No rationale provided.')}",
            f"  - Recommended fix: {_text(_get(flag, 'recommended_fix'), 'No fix provided.')}",
        ])
    return lines


def _format_string_list(items: list[Any], empty: str) -> list[str]:
    if not items:
        return [f"- {empty}"]
    return [f"- {str(item)}" for item in items]


def _component_rationale(account_score: Any, component_name: str) -> str:
    component = _get(account_score, component_name)
    if not component:
        return "No account score component available."
    score = _get(component, "score")
    rationale = _text(_get(component, "rationale"), "No rationale available.")
    return f"{score}/5 - {rationale}" if score is not None else rationale


def _strategy_angle(strategy: Any) -> str:
    angle = _get(strategy, "angle_name") or _get(strategy, "recommended_angle")
    rationale = _get(strategy, "rationale") or ""
    return f"{angle} - {rationale}" if angle and rationale else _text(angle or rationale, "No strategy available.")


def _score_value(account_score: Any) -> str:
    value = _get(account_score, "overall_score")
    return str(value) if value is not None else "Unknown"


def _quality_value(critic_result: Any) -> str:
    value = _get(critic_result, "overall_quality")
    return f"{float(value):.1f}/5" if value is not None else "Unknown"


def _title_terms(titles: list[str]) -> list[str]:
    terms: set[str] = set()
    for title in titles:
        cleaned = re.sub(r"[^a-z0-9 ]+", " ", (title or "").lower())
        words = [word for word in cleaned.split() if len(word) > 2]
        terms.update(words)
        if cleaned.strip():
            terms.add(cleaned.strip())
    return sorted(terms, key=len, reverse=True)


def _get(obj: Any, path: str, default: Any = None) -> Any:
    current = obj
    for part in path.split("."):
        if current is None:
            return default
        if isinstance(current, dict):
            current = current.get(part, default)
        else:
            current = getattr(current, part, default)
    return current


def _text(value: Any, fallback: str) -> str:
    if value is None:
        return fallback
    text = str(value).strip()
    return text if text else fallback


def _readable(value: Any) -> str:
    return str(value or "").replace("_", " ").strip().title()
